website/peptides/urls.py
from django.urls import path

from . import views

app_name = 'peptides'
urlpatterns = [
    path('', views.index_view, name='index'),
    path('about', views.about_view, name='about'),
    path('alignments/<str:acc_nums>/', views.alignments_view, name='alignments'),
    path('download_alignment/<str:prots>/', views.download_alignment, name='download_alignment'),
    path('get_protein/', views.get_protein, name='get_protein'),
    path('interaction_plot/<str:acc_num>', views.interaction_plot_show, name='interaction_plot'),
    path('download_interaction_plot_data/<str:acc_num>', views.download_interaction_plot_data, name='download_interaction_plot_data'),
    path('peptides/', views.peptides_csv, name='peptides'),
    path('proteins/<str:acc_num>/', views.protein_view, name='proteins'),
    path('proteins/<str:acc_num>/json', views.protein_json, name='proteins_json'),
    path('proteins/json_schema', views.protein_json_schema, name = 'protein_json_schema'),
    path('request_alignment/', views.request_alignment, name='request_alignment'),
    path('site_map', views.site_map, name='site_map'),
]

website/website/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.generic import RedirectView

urlpatterns = [
    re_path(r'^favicon\.ico$',RedirectView.as_view(url='/static/images/favicon.ico')),
    path('', 
        include(('peptides.urls', 'peptides'), namespace='peptides')
    ),
    path('admin/', admin.site.urls),
]

website/peptides/models.py
import re
from django.contrib import admin
from django.db import models

class BaseModel(models.Model):
    class Meta:
        app_label = 'peptides'
        abstract = True


is_acc_num = re.compile(
    ("(?:[OPQ][0-9][A-Z0-9]{3}[0-9]" # first style, e.g., P56856
    "|[A-NR-Z][0-9]([A-Z][A-Z0-9]{2}[0-9]){1,2})" # second style, e.g., A2BC19, A0A023GPI8
    "(?:-([1-9][0-9]*))?") # optional isoform number, e.g., -2, -10
).fullmatch

def isoform_num(acc_num: str) -> int:
    acc_num_split = acc_num.split('-')
    if len(acc_num_split) == 1:
        return 1
    return int(acc_num_split[1])


class Protein(BaseModel):
    prot_id = models.AutoField(primary_key=True)
    acc_num = models.CharField(max_length=15, unique=True)
    sequence = models.CharField(max_length=45_000)
    isoform_num = models.IntegerField(default = 1)
    # longest protein ever found is titin, with ~35,000 aa

    class Meta:
        indexes = [
            models.Index(fields = ['acc_num'], name = 'acc_num_idx')
        ]

    def __str__(self) -> str:
        return self.acc_num

    def __repr__(self) -> str:
        return 'Protein(%s)' % self.acc_num

    def save(self, *args, **kwargs):
        '''when protein saved, update the location of each associated 
        peptide to reflect its location in the protein.
        Also save the isoform number of the protein 
        (e.g., BLUTEN-1 has isoform # 1, BLUTEN-3 has isoform # 3)
        '''
        self.isoform_num = isoform_num(self.acc_num)
        super().save(*args, **kwargs)
        for peptide in Peptide.objects.filter(prot = self.acc_num):
            peptide.save(force_update=True)

    def get_isoforms(self):
        '''Return all protein objects that are isoforms of self
        '''
        # if this is the primary isoform, this will get all isoforms
        isos_2 = Isoform.objects.filter(prot_1 = self)
        if not isos_2:
            # this is a secondary isoform, or has no isoforms
            isos_1 = Isoform.objects.filter(prot_2 = self)
            if not isos_1:
                return [] # no isoforms
            # get the primary isoform, then get all isoforms of the primary
            primary_iso = isos_1.values('prot_1')[0]['prot_1']
            other_isos = Isoform.objects.filter(prot_1 = primary_iso)
            all_isos = isos_2.union(other_isos)
        else:
            all_isos = isos_2
        acc_nums = set()
        for iso in all_isos:
            acc_nums.add(iso.prot_1.acc_num)
            acc_nums.add(iso.prot_2.acc_num)
        acc_nums.remove(self.acc_num)
        return (Protein.objects.filter(acc_num__in = acc_nums)
            .order_by('isoform_num'))


    def get_alignments(self):
        '''return all alignment objects where self is one of the aligned
        proteins
        '''
        # equivalent to SELECT * FROM Alignment WHERE prots LIKE '%{acc_num}%'
        return Alignment.objects.filter(prots__contains = self.acc_num)

    def get_peptides(self):
        '''Return all peptides (in the Peptide table) associated with self
        '''
        return (Peptide.objects
            .filter(prot = self.acc_num)
            .order_by('location')
        )


class Isoform(BaseModel):
    pkey = models.AutoField(primary_key=True)
    prot_1 = models.ForeignKey(Protein, on_delete=models.CASCADE, related_name='prot_1')
    prot_2 = models.ForeignKey(Protein, on_delete=models.CASCADE, related_name='prot_2')

    def __str__(self) -> str:
        return "Isoform(%s, %s)" % (self.prot_1, self.prot_2)

    __repr__ = __str__


class Alignment(BaseModel):
    prots = models.CharField(max_length=300, primary_key=True)
    alignment = models.CharField(max_length=720_000)


class Peptide(BaseModel):
    pkey = models.AutoField(primary_key=True)
    prot = models.CharField(max_length=15)
    peptide = models.CharField(max_length=10_000)
    location = models.IntegerField(default=-1)

    def __str__(self):
        if len(self.peptide) > 20:
            prot_abbrev = self.peptide[:17] + '...'
        else: prot_abbrev = self.peptide
        return 'Peptide(%s, %i, %s)' % (self.prot, self.location, prot_abbrev)

    __repr__ = __str__

    def save(self, *args, **kwargs):
        '''Find the protein with this peptide's accession number, and if that
        protein is in the database, set the location field to the location
        of this peptide in that protein's sequence.
        '''
        corresponding_protein = Protein.objects.filter(acc_num = self.prot)
        if len(corresponding_protein) == 0:
            super().save(*args, **kwargs)
            return
        try:
            self.location = corresponding_protein[0].sequence.index(self.peptide)
        except ValueError: # raised by .index if thing not in list
            pass
        super().save(*args, **kwargs)

    @admin.display
    def peptide_preview(self):
        if len(self.peptide) < 20:
            return self.peptide
        return self.peptide[:17] + '...'
    
    class Meta:
        indexes = [
            models.Index(fields = ['prot'], name = 'prot_idx')
        ]

website/peptides/views.py
# lib libraries
import json
import logging
from pathlib import Path
import re
import traceback
# 3rd party libraries
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
# from django.views.decorators.cache import never_cache
from requests import Timeout

from .align_isoforms import get_isoforms, get_all_seqs, request_multi_alignment, get_protein as uniprot_json, align_isoforms
from .models import Protein, Peptide, Isoform, Alignment, is_acc_num
from .sequence_chunkers import sequence_chunks, process_clustal_num
from . import interaction_plot

CODE_DIR = Path(__file__).parent

def index_view(request):
    '''Show only the primary isoforms of proteins in the database.
    Optionally allow to order by length, by number of isoforms,
    or alphabetically.
    '''
    proteins = Protein.objects.filter(isoform_num = 1)
    data = [
        {
            'acc_num': prot.acc_num,
            'npeps': len(prot.get_peptides()),
            'lenseq': len(prot.sequence),
            'n_isoforms': len(prot.get_isoforms()) + 1,
            'has_alignment': 'Yes' if len(prot.get_alignments()) > 0 else 'No',
        }
        for prot in proteins
    ]
    orderby = request.GET.get('orderby', 'alpha')
    sort_reverse = orderby[0] == '-'
    if sort_reverse:
        orderby = orderby[1:]
    orderby = {
        'alpha': 'acc_num',
        'iso': 'n_isoforms',
        'len': 'lenseq',
        'npeps': 'npeps',
        'align': 'has_alignment',
    }.get(orderby, 'acc_num') # sort by accession number unless user says otherwise
    return render(
        request,
        'peptides/index.html',
        context = {
            'prot_data': data, 
            'orderby': orderby, 
            'sort_reverse': "true" if sort_reverse else "false"
        }
        # sorting is done server-side; see script at top of index.html
    )


def about_view(request):
    return render(request, 'peptides/about.html')


def protein_view(request, acc_num: str):
    try:
        width = int(request.GET.get('width', 120))
    except:
        width = 120
    num_offset = 10 + 9 * width
    if acc_num.endswith('-1'):
        acc_num = acc_num[:-2]
        # the primary isoform may end with '-1', but it doesn't
        # matter and it's really just confusing
    prot = get_object_or_404(Protein, acc_num = acc_num)
    alignments = prot.get_alignments()
    isoforms = prot.get_isoforms()
    peptides = prot.get_peptides()
    chunks = sequence_chunks(prot.sequence, peptides, width)
    annotated_chunks = []
    chunk_end = 0
    for chunk in chunks:
        chunk_end += sum(len(p['seq']) for p in chunk)
        annotated_chunks.append(
            {'chunk': chunk, 'chunk_end': chunk_end}
        )
    return render(
        request,
        template_name='peptides/protein.html',
        context = {
            'protein': prot,
            'alignments': alignments,
            'isoforms': isoforms,
            'peptides': peptides,
            'sequence_chunks': annotated_chunks,
            'seq_len': len(prot.sequence),
            'num_offset': num_offset,
        }
    )


def get_all_data_related_to_prot(acc_num: str) -> tuple:
    '''Get all isoforms of protein with UniProt accession number acc_num,
    get a multiple sequence alignment of those isoforms,
    and for each peptide in the database that belongs to one of the isoforms,
    get its location in the sequence of that isoform.
    Return three bools:
    (got data for at least one isoform,
    got data for multiple isoforms)
    '''
    prot_seqs, alignment = align_isoforms(acc_num)
    if not prot_seqs:
        return False, False
    if len(prot_seqs) < 2:
        return True, False
    seq = prot_seqs[acc_num]
    og_prot = Protein(
        acc_num = acc_num, 
        sequence = seq
    )
    og_prot.save(force_insert=True)
    prot_list = ','.join(prot_seqs.keys())
    # add each isoform to the database
    for acc_num_2, seq in prot_seqs.items():
        if acc_num_2 == acc_num:
            continue
        if acc_num_2.endswith('-1'):
            acc_num_2 = acc_num_2[:-2]
        prot = Protein(
            acc_num = acc_num_2, 
            sequence = seq
        )
        prot.save(force_insert=True)
        # also add a relationschip between og_prot and new prot
        Isoform.objects.create(
            prot_1 = Protein.objects.get(acc_num = acc_num),
            prot_2 = Protein.objects.get(acc_num = acc_num_2)
        )
    if isinstance(alignment, str):
        Alignment.objects.create(prots = prot_list, alignment = alignment)
    return True, True


def get_protein(request):
    try:
        acc_num = request.POST['acc_num']
    except:
        return render(request, 'peptides/get_protein.html')
    else:
        if acc_num.endswith('-1'):
            acc_num = acc_num[:-2]
        try:
            existing_prot = Protein.objects.get(acc_num = acc_num)
            return HttpResponseRedirect(
                reverse('peptides:proteins', args=(existing_prot.acc_num,))
            )
        except: # no existing prot, so get the data
            pass
        one_prot, multi_prots = get_all_data_related_to_prot(acc_num)
        if not one_prot:
            response = HttpResponse(
                "Could not find UniProt data for the accession number " + acc_num
            )
            response.status_code = 500
            return response
        elif not multi_prots:
            response = HttpResponse(
                f"We could only find one isoform of the protein with UniProt accession number {acc_num} on UniProt."
            )
            response.status_code = 500
            return response
        return HttpResponseRedirect(
            reverse('peptides:proteins', args=(acc_num,))
        )


def alignments_view(request, acc_nums: str):
    try:
        width = int(request.GET.get('width', 60))
    except:
        width = 60
    num_offset = 120 + 9 * width
    alignment = get_object_or_404(Alignment, pk=acc_nums)
    acc_num_list = acc_nums.split(',')
    prot_objs = (Protein.objects
        .filter(acc_num__in = acc_num_list)
        .order_by('isoform_num')
    )
    peptides =  (Peptide.objects
        .filter(prot__in = acc_num_list)
        .order_by('prot', 'location')
    )
    alignment_pieces = process_clustal_num(alignment.alignment, peptides, width)
    return render(
        request,
        'peptides/alignment.html',
        context = {
            'prots': alignment.prots,
            'alignment_pieces': alignment_pieces,
            'proteins': prot_objs,
            'peptides': peptides,
            'num_offset': num_offset,
        }
    )


def download_alignment(request, prots: str):
    alignment = Alignment.objects.get(pk = prots)
    primary_acc_num = alignment.prots.split(',')[0]
    try:
        dash_index = primary_acc_num.index('-')
        # all isoforms have the same alignment as the primary isoform
        primary_acc_num = primary_acc_num[:dash_index]
    except: pass
    # this disposition indicates that it should be downloaded with this default file name
    disposition =  'attachment; filename = "isoforms of %s alignment.clustal_num"' % primary_acc_num
    # this content-type indicates that this is a utf-8 text file
    content_type = 'text; charset = "utf-8"'
    return HttpResponse(
        alignment.alignment,
        headers = {'content-disposition': disposition, 'content-type': content_type},
    )


def protein_json(request, acc_num: str):
    prot = Protein.objects.get(acc_num = acc_num)
    isoform_ids = [iso.acc_num for iso in prot.get_isoforms()]
    alignments = [al.alignment for al in prot.get_alignments()]
    peptides = [{'location': pep.location, 'sequence': pep.peptide} 
        for pep in prot.get_peptides()]
    return JsonResponse(
        {
            'UniProt ID': prot.acc_num,
            'sequence': prot.sequence,
            'Isoform UniProt IDs': isoform_ids,
            'isoform alignments': alignments,
            'mass spec peptides': peptides, 
        }
    )


def protein_json_schema(request):
    schema_fname = CODE_DIR/'static'/'peptides'/'protein_json_schema.json'
    with schema_fname.open() as f:
        schema = json.load(f)
    return JsonResponse(schema)


def peptides_csv(request):
    '''Return a csv containing responsive accession numbers.
    Query must be of the form 'acc_num_like=<partial accession number>'
        or 'acc_num=<exact accession number>', or no query at all.
    If no query, return a csv returning all peptides.
    If acc_num query, return only the peptides for that accession number.
    If acc_num_like query, return peptides where the accession number
        contains the acc_num_like substring.
    '''
    acc_num_like = request.GET.get('acc_num_like', '')
    acc_num = request.GET.get('acc_num', '')
    if acc_num_like:
        if not re.fullmatch(r'[A-Z\d-]{6,10}', acc_num_like):
            return HttpResponse('Invalid accession number pattern')
        filename =  'peptides of uniprot ids like %s.csv' % acc_num_like
        peptides = (Peptide.objects
            .filter(prot__contains = acc_num_like)
            .order_by('prot', 'location')
        )
    elif acc_num:
        if not is_acc_num(acc_num):
            return HttpResponse('Invalid accession number')
        filename = 'peptides of uniprot id %s.csv' % acc_num
        peptides = (Peptide.objects
            .filter(prot = acc_num)
            .order_by('prot', 'location')
        )
    else:
        filename = 'peptides.csv'
        peptides = Peptide.objects.order_by('prot', 'location')
        if len(peptides) == 0:
            return HttpResponse('There are no peptides currently in the database.')
    if len(peptides) == 0:
        prots_with_acc_num = None
        if acc_num:
            prots_with_acc_num = Protein.objects.filter(acc_num = acc_num)
            if prots_with_acc_num:

website/peptides/templates/peptides/about.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        {% load static %}
        <title>About the isoform alignment mass spec peptide finder</title>
        <link rel="stylesheet" href="{% static 'peptides/css/main.css' %}">
        <link rel="stylesheet" href="{% static 'peptides/css/protein.css' %}">
    </head>
    <body>
        <h1>About the website</h1>
        <p><a href="/">Back to proteins list</a></p>
        <p>The purpose of this site is to educate biologists about the possibility
            of using mass spectrometric data to differentiate between splicing variants
            (hereafter called <em>isoforms</em>) of proteins that have some harmless
            isoforms and others that are potentially oncogenic.
        </p>
        <p>
            The site was constructed on behalf of biology professor 
            <a href="https://biology.sfsu.edu/les-timpe">Les Timpe</a>, who has been
            studying this topic for some time.
        </p>
        <p>
            <a href="https://doi.org/10.1016/j.cell.2020.06.013">Gillette et al.</a>
            (2020, Cell 182, 200-225 July 9, 2020) created a database of peptides
            found in the mass spectra of different protein isoforms that differentiate
            between their splicing variants.
        </p>
        <p>
            An example of how this technique can be employed is shown below.
        </p>
        <div class="chunk">
            <p class="sequence"><!--
                --><span class="left-buffer">P56856</span><!--
                --><!--
                    --><!--
                        -->MSTTTCQVVAFLLSILGLAGCIAATGMDMWSTQDLYDNPV<!--
                    --><!--
                --><!--
                    --><!--
                        --><span class="peptide 40_P56856" id="40_P56856_0" style="color: red; font-weight: bold;">TSVFQYEGLWR</span><!--
                    --><!--
                --><!--
                    --><!--
                        -->SCVRQSSGF<!--
                    --><!--
                --><!--
            --><!--
                --><span class="right" style="left:660px">60</span><!-- peptide number at end of line
            --><!--
            --></p>
            <p class="sequence"><!--
                --><span class="left-buffer">P56856-2</span><!--
                --><!--
                    --><!--
                        -->MAVTACQGLGFVVSLIGIAGIIAATCMDQWSTQDLYNNPVTA<!--
                    --><!--
                --><!--
                    --><!--
                        --><span class="peptide 42_P56856-2" id="42_P56856-2_0" style="color: red; font-weight: bold;">VFNYQGLWR</span><!--
                    --><!--
                --><!--
                    --><!--
                        -->SCVR<!--
                    --><!--
                --><!--
                    --><!--
                        --><span class="peptide 55_P56856-2" id="55_P56856-2_0" style="color: red; font-weight: bold;">ESSGF</span><!--
                    --><!--
                --><!--
            --><!--
                --><span class="right" style="left:660px">60</span><!-- peptide number at end of line
            --><!--
            --></p>
        
            <p class="sequence"><!--
                --><span class="left-buffer"></span><!--
                --><!--
                    --><!--
                        -->*:.*:** :.*::*::*:** **** ** *******:****:**:*:********:****<!--
                    --><!--
                --><!--
            --><!--
            --></p>
        </div>
        <p>
            The red regions of the 
            <a href="https://www.uniprot.org/uniprotkb/P56856/entry">above proteins</a>
            are mass spec peptides found by Gillette et al. that can be used
            to differentiate between the isoforms. 
        </p>
        <p>
            This method is far from foolproof. The stochastic nature of protein fragmentation
            during mass spectrometry means that many proteins do not have peptides
            that are useful for this diagnostic purpose. However, by examining proteins
            with peptides in the database and using the visualizations tools on this website,
            hopefully it will become apparent how mass spectrometric data can be used 
            as a diagnostic tool to determine if an oncogenic variant of a protein is
            present in a tissue sample.
        </p>
        <footer>Copyright 2022 Mark Johnston Olson (mjolsonsfca@gmail.com)</footer>
    </body>
</html>

website/peptides/templates/peptides/alignment.html
<!DOCTYPE html>
<html lang = "en">
    <head>
        <meta charset="utf-8">
        <title>Detail for alignment {{alignment.prots}}</title>
        {% load static %}
        <link rel="stylesheet" href="{% static 'peptides/css/main.css' %}">
        <link rel="stylesheet" href="{% static 'peptides/css/protein.css' %}">
        <script src="{% static 'peptides/js/peptide_highlight.js' %}" defer></script>
    </head>
    <body>
        <h1>Alignment {{ prots }}</h1>
        <p><a href="/">Back to proteins list</a></p>
        <p id="header">
            <span class="left-buffer"></span>{{ alignment_pieces.header }}
        </p>
        {% for chunk in alignment_pieces.chunks %}
            <div class="chunk">
            {% for prot_pieces in chunk %}
                <p class = "sequence"><!--
                 --><span class="left-buffer">{{ prot_pieces.acc_num }}</span><!--
                 -->{% for piece in prot_pieces.chunk %}<!--
                     -->{% if piece.is_pep %}<!--
                         --><span class="peptide {{ piece.loc }}_{{ prot_pieces.acc_num }}" 
                                id="{{ piece.loc }}_{{ prot_pieces.acc_num }}_{{ piece.pep_num }}">{{ piece.seq }}</span><!--
                     -->{% else %}<!--
                         -->{{ piece.seq }}<!--
                     -->{% endif %}<!--
                 -->{% endfor %}<!--
             -->{% if prot_pieces.is_prot_chunk %}<!--
                 --><span class="right" style="left:{{ num_offset }}px">{{ prot_pieces.chunk_end }}</span><!-- peptide number at end of line
             -->{% endif %}<!--
             --></p>
            {% endfor %}
            </div>
            {% endfor %}
        <a class="button" href="/download_alignment/{{ prots }}">
            Download alignment as text file
        </a>
        <p>Associated proteins</p>
        <ol>
        {% for protein in proteins %}
            <li>
                <a href = "/proteins/{{protein.acc_num}}">{{protein.acc_num}}</a>
            </li>
        {% endfor %}
        </ol>
        <button onclick = "highlight_all_peptides();">
            Highlight all peptides
        </button>
        <p>Associated mass spec peptides</p>
        <ol>
        {% for peptide in peptides %}
            <li>
                <a class = "peptide-link" href = "#{{peptide.location}}_{{peptide.prot}}_0"
                    onclick = 'highlight_locs("{{ peptide.location }}_{{ peptide.prot }}");'>
                    {{peptide.prot}}@{{ peptide.location }}
                </a>:
                <span class="sequence">{{ peptide.peptide }}</span>
            </li>
        {% endfor %}
        </ol>
        <footer>Copyright 2022 Mark Johnston Olson (mjolsonsfca@gmail.com)</footer>
    </body>
</html>

website/peptides/templates/peptides/get_protein.html
<!DOCTYPE html>
<html lang = "en">
    <head>
        <meta charset="utf-8">
        <title>Get protein</title>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'peptides/css/main.css' %}">
    </head>
    <body>
        <h1>Find a new protein</h1>
        <p><a href="/">Back to proteins list</a></p>
        <form action = "{% url 'peptides:get_protein'  %}" method = "POST">
            <!-- need csf_token in POST forms to avoid CSRF attacks -->
            {% csrf_token %}
            <fieldset>
                <p><strong>Choose a protein accession number</strong></p>
                <input type="text" minlength="6" maxlength="10" required="required"
                pattern = "(?:[OPQ][0-9][A-Z0-9]{3}[0-9]|[A-NR-Z][0-9]([A-Z][A-Z0-9]{2}[0-9]){1,2})(?:-([1-9][0-9]*))?"
                name="acc_num" id="acc_num">
                <label for="acc_num">
                <a href="https://www.uniprot.org/help/accession_numbers">
                    Accession number
                </a></label>
            </fieldset>
            <input type="submit" value="Request data">
        </form>
        <div id="workflow_description">
            <p>
                To get the data on a protein's sequence, its isoforms, 
                and its sequence alignment with its isoforms,
                the following steps are taken:
            </p>
            <ol>
                <li>
                    Request data from the 
                    <a href="https://rest.uniprot.org/docs/#/uniprotkb">
                        UniProtKB REST API</a>
                </li>
                <li>
                    Use the data to get the UniProt accession numbers
                    of the protein's isoforms.
                </li>
                <li>
                    Get the UniProt REST API data for each isoform.
                    Now we have the sequence of every isoform of the protein.
                </li>
                <li>
                    Use the European Bioinformatics Institute (EBI)'s
                    <a href = "https://www.ebi.ac.uk/Tools/msa/clustalo/">CLUSTAL-Omega tool</a>
                    to request a multiple sequence alignment of all the isoforms of the protein.
                    <strong>This step can take a <em>long time</em>, but usually only takes a few seconds.</strong>
                </li>
                <li>
                    Finally, cross-reference the unique peptides found by <a href="https://doi.org/10.1016/j.cell.2020.06.013">Gillette et al.</a> (2020, Cell 182, 200-225 July 9, 2020)
                </li>
            </ol>
        </div>
        <footer>Copyright 2022 Mark Johnston Olson (mjolsonsfca@gmail.com)</footer>
    </body>
</html>

website/peptides/templates/peptides/protein.html
<!DOCTYPE html>
<html lang = "en">
    <head>
        <meta charset="utf-8">
        <title>Protein detail for {{ protein.acc_num }}</title>
        {% load static %}
        <link rel="stylesheet" href="{% static 'peptides/css/main.css' %}">
        <link rel="stylesheet" href="{% static 'peptides/css/protein.css' %}">
        <script src="{% static 'peptides/js/peptide_highlight.js' %}" defer></script>
    </head>
    <body>
        <h1>Protein {{ protein.acc_num }} detail</h1>
        <p><a href="/">Back to proteins list</a></p>
        <p><a href="https://www.uniprot.org/uniprotkb/{{protein.acc_num}}/entry">
            UniProt entry for {{ protein.acc_num }}
        </a></p>
        <p>
            <a href="/proteins/{{ protein.acc_num }}/json">
            Get all data for this protein as JSON
            </a>
            (view 
            <a href = "/proteins/json_schema">schema</a>)
        </p>
        <p>Isoforms:</p>
        <ol>
        {% for isoform in isoforms %}
            <li>
                <a href="/proteins/{{ isoform }}">Isoform {{ isoform }}</a>
            </li>
        {% endfor %}
        </ol>
        <p>Alignments:</p>
        {% if alignments|length_is:"0" %}
            <form action = "{% url 'peptides:request_alignment'  %}" method = "POST">
                {% csrf_token %}
                <input hidden type="text" value="{{ protein.acc_num }}" name="acc_num" id="acc_num">
                <input type="submit" value="Alignment not found for {{ protein.acc_num }}. Try again?">
            </form>
        {% endif %}
        <ul>
        {% for alignment in alignments %}
            <li>
                <a href="/alignments/{{ alignment.prots }}">Alignment {{ alignment.prots }}</a>
            </li>
        {% endfor %}
        </ul>
        <p>
            <a href="/interaction_plot/{{ protein.acc_num }}">Plot MS intensities of isoforms in cancer vs. non-cancer tissue samples</a>
        </p>
        <p>Sequence (length {{seq_len}}):</p>
        <div class="chunk">
        {% for prot_pieces in sequence_chunks %}
            <p class = "sequence"><!--
             -->{% for piece in prot_pieces.chunk %}<!--
                 -->{% if piece.is_pep %}<!--
                     --><span class="peptide {{ piece.loc }}" 
                              id="{{ piece.loc }}_{{ piece.pep_num }}">{{ piece.seq }}</span><!--
                 -->{% else %}<!--
                     -->{{ piece.seq }}<!--
                 -->{% endif %}<!--
             -->{% endfor %}<!--
         --><span class="right" style="left:{{ num_offset }}px">{{ prot_pieces.chunk_end }}</span><!-- peptide number at end of line
         --></p>
        {% endfor %}
        </div>
        <button onclick = "highlight_all_peptides();">
            Highlight all peptides
        </button>
        {% if peptides|length_is:"0" %}
            <p>No mass spec peptides unique to this isoform.</p>
        {% else %}
            <p>Mass spec peptides unique to this isoform:</p>
            <ul>
            {% for peptide in peptides %}
                <li>
                    <a class = "peptide-link" href = "#{{peptide.location}}_0"
                        onclick = 'highlight_locs("{{ peptide.location }}");'>
                        @{{ peptide.location }}
                    </a>:
                    <span class="sequence">{{ peptide.peptide }}</span>
                </li>
            {% endfor %}
            </ul>
        {% endif %}
        <footer>Copyright 2022 Mark Johnston Olson (mjolsonsfca@gmail.com)</footer>
    </body>
</html>